<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18099" started-at="2020-04-10T18:04:39 CEST" finished-at="2020-04-10T18:04:57 CEST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18099" started-at="2020-04-10T18:04:39 CEST" finished-at="2020-04-10T18:04:57 CEST">
      <class name="samsara.XorTest">
        <test-method status="PASS" signature="initialize()[pri:0, instance:samsara.XorTest@21b2e768]" name="initialize" is-config="true" duration-ms="7386" started-at="2020-04-10T18:04:39 CEST" finished-at="2020-04-10T18:04:46 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testFactorial(java.lang.String, java.lang.String, java.lang.String, char)[pri:0, instance:samsara.XorTest@21b2e768]" name="testFactorial" duration-ms="1733" started-at="2020-04-10T18:04:46 CEST" data-provider="getData" finished-at="2020-04-10T18:04:48 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[samasa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[s]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[XOR isn't as expected. expected [QS] but found [QS]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: XOR isn't as expected. expected [QS] but found [QS]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at samsara.XorTest.testFactorial(XorTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial -->
        <test-method status="FAIL" signature="testFactorial(java.lang.String, java.lang.String, java.lang.String, char)[pri:0, instance:samsara.XorTest@21b2e768]" name="testFactorial" duration-ms="2577" started-at="2020-04-10T18:04:48 CEST" data-provider="getData" finished-at="2020-04-10T18:04:50 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[samasa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[s]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[XOR isn't as expected. expected [?'
0>] but found [?' 0>]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: XOR isn't as expected. expected [?'
0>] but found [?' 0>]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at samsara.XorTest.testFactorial(XorTest.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial -->
        <test-method status="PASS" signature="testFactorial(java.lang.String, java.lang.String, java.lang.String, char)[pri:0, instance:samsara.XorTest@21b2e768]" name="testFactorial" duration-ms="4207" started-at="2020-04-10T18:04:50 CEST" data-provider="getData" finished-at="2020-04-10T18:04:54 CEST">
          <params>
            <param index="0">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[samasa]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[s]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFactorial -->
        <test-method status="PASS" signature="testAlgorithmsSamsaraAfter()[pri:0, instance:samsara.XorTest@21b2e768]" name="testAlgorithmsSamsaraAfter" is-config="true" duration-ms="2115" started-at="2020-04-10T18:04:54 CEST" finished-at="2020-04-10T18:04:57 CEST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAlgorithmsSamsaraAfter -->
      </class> <!-- samsara.XorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
